### ISSUE TITLE
onPress prop?

### ISSUE THREAD

**Issue by karanpratapsingh** [cawfree/react-native-segmented-text-input#1]
Great work as always, I was wondering if `onPress` can be added as an optional prop.

**Comment by cawfree** [comment]
Thanks a lot Karan!

The way it is currently configured is that each type of regexp you’re
looking for maps to an equivalent component; so it is at the component
stage you can define the onPress. If you check out the source, you’ll see
that the regexp for a mention maps to a TouchableOpacity:

https://github.com/cawfree/react-native-segmented-text-input/blob/f539a15d530b31fe5c1ff682c1c1165657300d34/src/index.js#L248

(Unless I’m completely misunderstanding your question, of course!) 😂

**Comment by karanpratapsingh** [comment]
Awesome, can't wait to try this 🚀
