### ISSUE TITLE
How to use custom pettern?

### ISSUE THREAD

**Issue by m0w4hhed** [cawfree/react-native-segmented-text-input#2]
my pettern in useState:
`const [value, onChange] = useState(['', ["[a-z\d -]+(?=,)+"]]);`

but got an error:
`Error: Text strings must be rendered within a <Text> component`

this is my pettern what i need: https://regex101.com/r/0YhNBz/2

**Comment by cawfree** [comment]
You need to declare this as using the [`patterns`](https://github.com/cawfree/react-native-segmented-text-input/blob/148698ba09807bb7e867d9804bb043a09d22a913/src/index.js#L265) prop.

So it would look something along the lines of (untested!):

```javascript
import React from "react";
import { Text } from "react-native";
import SegmentedTextInput from "react-native-segmented-text-input";

<SegmentedTextInput
  {...extras}
  patterns={{
    ["[a-z\d -]+(?=,)+"]: Text,
  }}
/>
```

**Comment by m0w4hhed** [comment]
it didnt work man

**Comment by cawfree** [comment]
Hi @m0w4hhed, can you provide a minimum reproducable example? How do you expect the words to be separated?
